<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>disable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <SelfContained>true</SelfContained>
        <PublishSingleFile>true</PublishSingleFile>
        <PublishTrimmed>true</PublishTrimmed>
        <TrimMode>full</TrimMode>
        <IsPublishable>true</IsPublishable>
        <IsPackable>false</IsPackable>
        <Version>1.0.0</Version>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="PdfPig" Version="0.1.12"/>
        <PackageReference Include="CsvHelper" Version="33.1.0"/>
    </ItemGroup>

    <ItemGroup>
        <TrimmerRootDescriptor Include="linker.xml"/>
    </ItemGroup>

</Project>
